version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-carsphere'
    environment:
      - 'POSTGRES_DB=carsphere_db'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carsphere-network

volumes:
  postgres_data:

networks:
  carsphere-network:
